/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideoRouteImport } from './routes/video'
import { Route as MessageRouteImport } from './routes/message'
import { Route as CountdownRouteImport } from './routes/countdown'
import { Route as IndexRouteImport } from './routes/index'

const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)
const MessageRoute = MessageRouteImport.update({
  id: '/message',
  path: '/message',
  getParentRoute: () => rootRouteImport,
} as any)
const CountdownRoute = CountdownRouteImport.update({
  id: '/countdown',
  path: '/countdown',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/countdown': typeof CountdownRoute
  '/message': typeof MessageRoute
  '/video': typeof VideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/countdown': typeof CountdownRoute
  '/message': typeof MessageRoute
  '/video': typeof VideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/countdown': typeof CountdownRoute
  '/message': typeof MessageRoute
  '/video': typeof VideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/countdown' | '/message' | '/video'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/countdown' | '/message' | '/video'
  id: '__root__' | '/' | '/countdown' | '/message' | '/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountdownRoute: typeof CountdownRoute
  MessageRoute: typeof MessageRoute
  VideoRoute: typeof VideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/message': {
      id: '/message'
      path: '/message'
      fullPath: '/message'
      preLoaderRoute: typeof MessageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countdown': {
      id: '/countdown'
      path: '/countdown'
      fullPath: '/countdown'
      preLoaderRoute: typeof CountdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountdownRoute: CountdownRoute,
  MessageRoute: MessageRoute,
  VideoRoute: VideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
